### ISSUE TITLE
[BUG]: TS types broken in v5

### ISSUE THREAD

**Issue by liamjones** [wix/sentry-testkit#138]
**Describe the bug**
Ran `tsc` against our project after upgrading sentry-testkit to 5.0.0:

```
packages/modules/application/__tests__/core/application/reportError.test.ts:3:52 - error TS7016: Could not find a declaration file for module 'sentry-testkit'. '/Users/liam.jones/code/proj/node_modules/sentry-testkit/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/sentry-testkit` if it exists or add a new declaration (.d.ts) file containing `declare module 'sentry-testkit';`

3 import sentryTestkit, { Report, ReportError } from 'sentry-testkit'
                                                     ~~~~~~~~~~~~~~~~
```

**To Reproduce**
Try and type check a project against 5.0.0

**Expected behavior**
Type check passes

**Sentry Versions (please complete the following information):**
 - Sentry: 4.6.1
 - Sentry-Testkit 5.0.0

**Comment by liamjones** [comment]
I think this is happening because the `package.json` says:

`"types": "index.d.ts"`

and that file doesn't exist.

**Comment by zivl** [comment]
@liamjones thanks for upgrading and report this right away, I was missing the right pointer for the types file in `package.json`, sorry for the sloppiness here

**Comment by liamjones** [comment]
It's moved on but it's still not happy. Cmd+clicking through to types shows it's finding `dist/index.d.ts` but that has been generated as an empty object:

```javascript
export {};
//# sourceMappingURL=index.d.ts.map
```

**Comment by zivl** [comment]
I released `sentry-testkit@5.0.2`. It resolves the empty export thing, but not yet complete solution.
Since I'm trying to support both `Sentry v6` and `Sentry v7` (btw, is this working for you on `Sentry v4`?, I have issues with `sentryTransport` signature:
```typescript
transport: sentryTransport,
^^^^^^^^^
```
I see that you're the TS expert who brought us [this](https://github.com/wix/sentry-testkit/blob/5a59dbd19e2307602f3c2f8e8a0641412b8e1c91/index.d.ts#L73):
```typescript
  type V6TransportClass = {
    new (): Transport
  }

  type V7TransportFunction = () => Transport
```

We're at the weekend here, I'd appreciate if you can help and PR or we will wait for next week, when I can get my colleagues to work on it.

**Comment by zivl** [comment]
released version `sentry-testkit@5.0.3` where `sentryTransport: any` so TS compiler won't show errors for now

**Comment by zivl** [comment]
closing this bug as it has been resolved.
opening different issue https://github.com/wix/sentry-testkit/issues/142 to handle better typings for `sentryTransport`

**Comment by liamjones** [comment]
> We're at the weekend here, I'd appreciate if you can help and PR or we will wait for next week, when I can get my colleagues to work on it.

@zivl apologies, I was on holiday last week and I've only just seen this. I'll see if I can take a look on the new issue this week sometime.

**Comment by zivl** [comment]
@liamjones sure thing!
Thanks :)
